### ISSUE TITLE
Replace uses of deprecated token methods

### ISSUE THREAD

**Issue by DannyS712** [Krinkle/mw-tool-tourbot#16]
Would it be possible for tourbot to replace the uses of the api token methods discussion at https://phabricator.wikimedia.org/T248288?

Specifically:
* action=query&list=recentchanges&rctoken=
* action=query&prop=revisions&rvtoken=
* action=query&meta=userinfo&uiprop=preferencestoken (or multiple values that include `preferencestoken`)
* action=query&list=users&ustoken=
* action=tokens

**Comment by Amorymeltzer** [comment]
At the very least, I would naïvely think the last one (`action=tokens` -> `action=query&meta=tokens`) would be difficult given the structure of the response will be changing.

**Comment by Krinkle** [comment]
Tourbot is for updating use of JavaScript interfaces, mainly to prevent cascading failurre, but also more generally because the people using this tool as experienced JavaScript developers.

Task T248288 is about an HTTP API via api.php, which is not JavaScript code. Changing URLs and API queries is a different domain, and not one I consider myself a foremost expert in and is not something I would do as part of tourbot runs. They're also significantly harder to have statically obtainable confidence in. The stakes are imho also lower because the worst that can happen is that the API query returns a warning or error, which the code generally already handles and informs users about. It doesn't tend to cause cascading failure or invisible failure as with script errors. And, the MW developers changing these APIs are expected to know the bots and gadgets using these deprecated features and can do targetted outreach to consumers before removing them.
