### ISSUE TITLE
Show details of errors causing it to skip editing a file

### ISSUE THREAD

**Issue by Krenair** [Krinkle/mw-tool-tourbot#8]
#6 made this not completely stop the process but we should display the reason, e.g. code like abusefilter-warning would be better than nothing

**Comment by Krinkle** [comment]
This depends on upstream MediaWiki deprecating using non-standard ways of exposing error information. For most errors, hook aborts and other ways of rejecting an edit are already caught and reported through `data.error`, detected by nodemw, and forwarded to the appropiate handler here, and reported to standard out.

But for AbuseFilter specifically, it still uses the ad-hoc `apiHookResult` property on the Status object from the `EditFilterMergedContent` hook to manually create a response object. There only standardised property in that object is `result = "Failure"`, which is already represented as "Edit failed". Anything else will be specific to AbuseFilter/SpamBlacklist/ConfirmEdit etc. and mainly intended for its frontend to consume, not by anything else.

**Comment by Krinkle** [comment]
In nodemw 0.10 the internal API `call()` sees the request as non-error because there is no data.error value. Later in `doEdit()` it then checks `!err && data.result == "Success"` which fails given result is Failure, at which point it invoked the callback with `new Error( "Edit failed: ${err}" )` which produces null because `call()` did not find any error.

In nodem 0.11 this got worse, see <https://github.com/macbre/nodemw/issues/131>

**Comment by Krinkle** [comment]
Seems to work now.
